### ISSUE TITLE
Seeds path `/vendor/cakedc/users/config/Seeds` does not exist and cannot be created because `debug` is disabled.

### ISSUE THREAD

**Issue by challgren** [CakeDC/users#1010]
Using the following configurations

CakePHP version 4.4.8
CakeDC/Users 11.2.0
CakeDC/Auth 7.2.0
cakephp/migrations 3.6.1/3.7.0
robmorgan/phinx 0.12.13/0.13.3
debug = false

The following error occurs when running `bin/cake migrations migrate -p CakeDC/Users`

```
2022-12-09 22:06:29 error: [RuntimeException] Seeds path `/var/www/html/vendor/cakedc/users/config/Seeds` does not exist and cannot be created because `debug` is disabled. in /var/www/html/vendor/cakephp/migrations/src/ConfigurationTrait.php on line 111
Stack Trace:
- /var/www/html/vendor/robmorgan/phinx/src/Phinx/Console/Command/AbstractCommand.php:346
- /var/www/html/vendor/robmorgan/phinx/src/Phinx/Console/Command/AbstractCommand.php:130
- /var/www/html/vendor/cakephp/migrations/src/Command/Phinx/CommandTrait.php:66
- /var/www/html/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php:64
- /var/www/html/vendor/cakephp/migrations/src/Command/Phinx/CommandTrait.php:37
- /var/www/html/vendor/cakephp/migrations/src/Command/Phinx/Migrate.php:85
- /var/www/html/vendor/symfony/console/Command/Command.php:312
- /var/www/html/vendor/symfony/console/Application.php:1020
- /var/www/html/vendor/symfony/console/Application.php:312
- /var/www/html/vendor/symfony/console/Application.php:168
- /var/www/html/vendor/cakephp/migrations/src/Command/MigrationsCommand.php:126
- /var/www/html/vendor/cakephp/cakephp/src/Console/BaseCommand.php:189
- /var/www/html/vendor/cakephp/migrations/src/Command/MigrationsCommand.php:198
- /var/www/html/vendor/cakephp/cakephp/src/Console/CommandRunner.php:334
- /var/www/html/vendor/cakephp/cakephp/src/Console/CommandRunner.php:172
- /var/www/html/bin/cake.php:16

2022-12-09 22:06:29 alert: Throwable: RuntimeException
2022-12-09 22:06:29 alert: A throwable: Seeds path `/var/www/html/vendor/cakedc/users/config/Seeds` does not exist and cannot be created because `debug` is disabled.
2022-12-09 22:06:29 alert: Trace: #0 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Console/Command/AbstractCommand.php(346): Migrations\Command\Phinx\Migrate->getConfig()
#1 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Console/Command/AbstractCommand.php(130): Phinx\Console\Command\AbstractCommand->loadManager(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/vendor/cakephp/migrations/src/Command/Phinx/CommandTrait.php(66): Phinx\Console\Command\AbstractCommand->bootstrap(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(64): Migrations\Command\Phinx\Migrate->bootstrap(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/vendor/cakephp/migrations/src/Command/Phinx/CommandTrait.php(37): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/vendor/cakephp/migrations/src/Command/Phinx/Migrate.php(85): Migrations\Command\Phinx\Migrate->parentExecute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/vendor/symfony/console/Command/Command.php(312): Migrations\Command\Phinx\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/vendor/symfony/console/Application.php(1020): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/vendor/symfony/console/Application.php(312): Symfony\Component\Console\Application->doRunCommand(Object(Migrations\Command\Phinx\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/vendor/cakephp/migrations/src/Command/MigrationsCommand.php(126): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/vendor/cakephp/cakephp/src/Console/BaseCommand.php(189): Migrations\Command\MigrationsCommand->execute(Object(Cake\Console\Arguments), Object(Cake\Console\ConsoleIo))
#12 /var/www/html/vendor/cakephp/migrations/src/Command/MigrationsCommand.php(198): Cake\Console\BaseCommand->run(Array, Object(Cake\Console\ConsoleIo))
#13 /var/www/html/vendor/cakephp/cakephp/src/Console/CommandRunner.php(334): Migrations\Command\MigrationsCommand->run(Array, Object(Cake\Console\ConsoleIo))
#14 /var/www/html/vendor/cakephp/cakephp/src/Console/CommandRunner.php(172): Cake\Console\CommandRunner->runCommand(Object(Migrations\Command\MigrationsMigrateCommand), Array, Object(Cake\Console\ConsoleIo))
#15 /var/www/html/bin/cake.php(16): Cake\Console\CommandRunner->run(Array)
#16 {main}
[RuntimeException] Seeds path `/var/www/html/vendor/cakedc/users/config/Seeds` does not exist and cannot be created because `debug` is disabled. in /var/www/html/vendor/cakephp/migrations/src/ConfigurationTrait.php on line 111

Stack Trace:

#0 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Console/Command/AbstractCommand.php(346): Migrations\Command\Phinx\Migrate->getConfig()
#1 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Console/Command/AbstractCommand.php(130): Phinx\Console\Command\AbstractCommand->loadManager(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/vendor/cakephp/migrations/src/Command/Phinx/CommandTrait.php(66): Phinx\Console\Command\AbstractCommand->bootstrap(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(64): Migrations\Command\Phinx\Migrate->bootstrap(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/vendor/cakephp/migrations/src/Command/Phinx/CommandTrait.php(37): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/vendor/cakephp/migrations/src/Command/Phinx/Migrate.php(85): Migrations\Command\Phinx\Migrate->parentExecute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/vendor/symfony/console/Command/Command.php(312): Migrations\Command\Phinx\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/vendor/symfony/console/Application.php(1020): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/vendor/symfony/console/Application.php(312): Symfony\Component\Console\Application->doRunCommand(Object(Migrations\Command\Phinx\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/vendor/cakephp/migrations/src/Command/MigrationsCommand.php(126): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/vendor/cakephp/cakephp/src/Console/BaseCommand.php(189): Migrations\Command\MigrationsCommand->execute(Object(Cake\Console\Arguments), Object(Cake\Console\ConsoleIo))
#12 /var/www/html/vendor/cakephp/migrations/src/Command/MigrationsCommand.php(198): Cake\Console\BaseCommand->run(Array, Object(Cake\Console\ConsoleIo))
#13 /var/www/html/vendor/cakephp/cakephp/src/Console/CommandRunner.php(334): Migrations\Command\MigrationsCommand->run(Array, Object(Cake\Console\ConsoleIo))
#14 /var/www/html/vendor/cakephp/cakephp/src/Console/CommandRunner.php(172): Cake\Console\CommandRunner->runCommand(Object(Migrations\Command\MigrationsMigrateCommand), Array, Object(Cake\Console\ConsoleIo))
#15 /var/www/html/bin/cake.php(16): Cake\Console\CommandRunner->run(Array)
#16 {main}
```

My guess is this is related to https://github.com/cakephp/migrations/pull/584 being implemented

**Comment by challgren** [comment]
Closing via https://github.com/cakephp/migrations/pull/597
