### ISSUE TITLE
[8.0] Can't register with Google

### ISSUE THREAD

**Issue by Josecanalla** [CakeDC/users#787]
Hello, I have 8.0 version of plugin and 3.6 CakePHP version.

If I want to register with Google account I get an error. If I want to login with Google with an account yet created, it works.

Log:

```
2019-04-22 07:37:54 Error: [InvalidArgumentException] No se puede iniciar sesión con el usuario con referencia 112022322960958371577
Request URL: /auth/google?state=b157c7a5243b771cdb3c5a1ba7c33878&code=4%2FNAFbOL-YovdR3MW1RZv6-oQ6t822MCw8WNX4Xj6nFXO-tv5khktacCo8QhelVHWgXKen-olPjZWyzFjJ3t2EvyM&scope=email+profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile&authuser=3&session_state=e636b3af38cab50e26eecadedef05f2ed6bbecb7..bdc8&prompt=none
Referer URL: https://accounts.google.com/signin/oauth/oauthchooseaccount?client_id=561021807442-vuk4gh3al7ofvbjiq7o1bs41mql3loln.apps.googleusercontent.com&as=8f8_mcVMCM2rvNzg9qnDgw&destination=https%3A%2F%2Fmysitega.com.ar&approval_state=!ChRaWEpNcFZKcF9xS3dFVzhrTGp1ZxIfSXdzbVdmVXhtSnNURUZvSEdUZHlJLTB0MVBoSnBCWQ%E2%88%99AJDr988AAAAAXL7q_FMKrcCfbA6W1fNavR1_GviaMvaD&oauthgdpr=1&xsrfsig=ChkAeAh8Tw5DjnzmfJtuIN0FlnP_NbOMLU4FEg5hcHByb3ZhbF9zdGF0ZRILZGVzdGluYXRpb24SBXNvYWN1Eg9vYXV0aHJpc2t5c2NvcGU&flowName=GeneralOAuthFlow
Stack Trace:
#0 [internal function]: CakeDC\Users\Model\Behavior\SocialBehavior->socialLogin(Array, Array)
#1 /home/mysite/public_html/vendor/cakephp/cakephp/src/ORM/BehaviorRegistry.php(253): call_user_func_array(Array, Array)
#2 /home/mysite/public_html/vendor/cakephp/cakephp/src/ORM/Table.php(2503): Cake\ORM\BehaviorRegistry->call('sociallogin', Array)
#3 /home/mysite/public_html/vendor/cakedc/users/src/Auth/SocialAuthenticate.php(484): Cake\ORM\Table->__call('socialLogin', Array)
#4 /home/mysite/public_html/vendor/cakedc/users/src/Auth/SocialAuthenticate.php(345): CakeDC\Users\Auth\SocialAuthenticate->_socialLogin(Array)
#5 /home/mysite/public_html/vendor/cakedc/users/src/Auth/SocialAuthenticate.php(419): CakeDC\Users\Auth\SocialAuthenticate->_touch(Array)
#6 /home/mysite/public_html/vendor/cakephp/cakephp/src/Controller/Component/AuthComponent.php(748): CakeDC\Users\Auth\SocialAuthenticate->getUser(Object(Cake\Http\ServerRequest))
#7 /home/mysite/public_html/vendor/cakephp/cakephp/src/Controller/Component/AuthComponent.php(312): Cake\Controller\Component\AuthComponent->_getUser()
#8 /home/mysite/public_html/vendor/cakephp/cakephp/src/Controller/Component/AuthComponent.php(276): Cake\Controller\Component\AuthComponent->authCheck(Object(Cake\Event\Event))
#9 /home/mysite/public_html/vendor/cakephp/cakephp/src/Event/EventManager.php(353): Cake\Controller\Component\AuthComponent->startup(Object(Cake\Event\Event))
#10 /home/mysite/public_html/vendor/cakephp/cakephp/src/Event/EventManager.php(330): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#11 /home/mysite/public_html/vendor/cakephp/cakephp/src/Event/EventDispatcherTrait.php(114): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#12 /home/mysite/public_html/vendor/cakephp/cakephp/src/Controller/Controller.php(675): Cake\Controller\Controller->dispatchEvent('Controller.star...')
#13 /home/mysite/public_html/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(115): Cake\Controller\Controller->startupProcess()
#14 /home/mysite/public_html/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(94): Cake\Http\ActionDispatcher->_invoke(Object(CakeDC\Users\Controller\UsersController))
#15 /home/mysite/public_html/vendor/cakephp/cakephp/src/Http/BaseApplication.php(235): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 /home/mysite/public_html/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#17 /home/mysite/public_html/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(156): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#18 /home/mysite/public_html/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#19 /home/mysite/public_html/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#20 /home/mysite/public_html/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#21 /home/mysite/public_html/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#22 /home/mysite/public_html/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#23 /home/mysite/public_html/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#24 /home/mysite/public_html/vendor/cakephp/cakephp/src/Http/Server.php(98): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#25 /home/mysite/public_html/webroot/index.php(37): Cake\Http\Server->run()
#26 {main}
```

**Comment by Josecanalla** [comment]
I updated plugin to 8.4 version and get the same error.
